from banksia import Metadata

__all__ = ["METADATA"]

METADATA: list[Metadata] = [
    Metadata(basename="BP9", label="Systolic blood pressure (cycling) - baseline"),
    Metadata(basename="BP10", label="Diastolic blood pressure (cycling) - baseline"),
    Metadata(basename="BP11", label="Heart rate (cycling) - baseline"),
    Metadata(basename="BP12", label="State (cycling) - baseline"),
    Metadata(basename="BP13", label="Heart rate (cycling - stage 1) - 1 min"),
    Metadata(basename="BP14", label="Heart rate (cycling - stage 1) - 2 mins"),
    Metadata(basename="BP15", label="Heart rate (cycling - stage 2) - 3 mins"),
    Metadata(basename="BP16", label="Heart rate (cycling - stage 2) - 4 mins"),
    Metadata(basename="BP17", label="Heart rate (cycling - stage 3) - 5 mins"),
    Metadata(basename="BP18", label="Heart rate (cycling - stage 3) - 6 mins"),
    Metadata(basename="BP21", label="Systolic blood pressure (post-cycling) - 1 min"),
    Metadata(basename="BP22", label="Diastolic blood pressure (post-cycling) - 1 min"),
    Metadata(basename="BP23", label="Heart rate (post-cycling) - 1 min"),
    Metadata(basename="BP24", label="State (post-cycling) - 1 min"),
    Metadata(basename="BP25", label="Systolic blood pressure (post-cycling) - 2 mins"),
    Metadata(basename="BP26", label="Diastolic blood pressure (post-cycling) - 2 mins"),
    Metadata(basename="BP27", label="Heart rate (post-cycling) - 2 mins"),
    Metadata(basename="BP28", label="State (post-cycling) - 2 mins"),
    Metadata(basename="BP29", label="Systolic blood pressure (post-cycling) - 3 mins"),
    Metadata(basename="BP30", label="Diastolic blood pressure (post-cycling) - 3 mins"),
    Metadata(basename="BP31", label="Heart rate (post-cycling) - 3 mins"),
    Metadata(basename="BP32", label="State (post-cycling) - 3 mins"),
    Metadata(basename="BP33", label="Systolic blood pressure (post-cycling) - 4 mins"),
    Metadata(basename="BP34", label="Diastolic blood pressure (post-cycling) - 4 mins"),
    Metadata(basename="BP35", label="Heart rate (post-cycling) - 4 mins"),
    Metadata(basename="BP36", label="State (post-cycling) - 4 mins"),
    Metadata(basename="BP37", label="Systolic blood pressure (post-cycling) - 5 mins"),
    Metadata(basename="BP38", label="Diastolic blood pressure (post-cycling) - 5 mins"),
    Metadata(basename="BP39", label="Heart rate (post-cycling) - 5 mins"),
    Metadata(basename="BP40", label="State (post-cycling) - 5 mins"),
    Metadata(basename="BP41", label="Systolic blood pressure (post-cycling) - 6 mins"),
    Metadata(basename="BP42", label="Diastolic blood pressure (post-cycling) - 6 mins"),
    Metadata(basename="BP43", label="Heart rate (post-cycling) - 6 mins"),
    Metadata(basename="BP44", label="State (post-cycling) - 6 mins"),
    Metadata(basename="BP82", label="Systolic blood pressure (cycling - stage 1) - 1.5 mins"),
    Metadata(basename="BP83", label="Diastolic blood pressure (cycling - stage 1) - 1.5 mins"),
    Metadata(basename="BP84", label="Heart rate (cycling - stage 1) - 1.5 mins"),
    Metadata(basename="BP85", label="Systolic blood pressure (cycling - stage 2) - 3.5 mins"),
    Metadata(basename="BP86", label="Diastolic blood pressure (cycling - stage 2) - 3.5 mins"),
    Metadata(basename="BP87", label="Heart rate (cycling - stage 2) - 3.5 mins"),
    Metadata(basename="BP88", label="Systolic blood pressure (cycling - stage 3) - 5.5 mins"),
    Metadata(basename="BP89", label="Diastolic blood pressure (cycling - stage 3) - 5.5 mins"),
    Metadata(basename="BP90", label="Heart rate (cycling - stage 3) - 5.5 mins"),
    Metadata(basename="BPS1", label="Systolic blood pressure (pre-sleep) - 0 mins"),
    Metadata(basename="BPS2", label="Systolic blood pressure (pre-sleep) - 2 mins"),
    Metadata(basename="BPS3", label="Systolic blood pressure (pre-sleep) - 4 mins"),
    Metadata(basename="BPS4", label="Systolic blood pressure (post-sleep) - 0 mins"),
    Metadata(basename="BPS5", label="Systolic blood pressure (post-sleep) - 2 mins"),
    Metadata(basename="BPS6", label="Systolic blood pressure (post-sleep) - 4 mins"),
    Metadata(basename="BPD1", label="Diastolic blood pressure (pre-sleep) - 0 mins"),
    Metadata(basename="BPD2", label="Diastolic blood pressure (pre-sleep) - 2 mins"),
    Metadata(basename="BPD3", label="Diastolic blood pressure (pre-sleep) - 4 mins"),
    Metadata(basename="BPD4", label="Diastolic blood pressure (post-sleep) - 0 mins"),
    Metadata(basename="BPD5", label="Diastolic blood pressure (post-sleep) - 2 mins"),
    Metadata(basename="BPD6", label="Diastolic blood pressure (post-sleep) - 4 mins"),
    Metadata(basename="SHR1", label="Heart rate (pre-sleep) - 0 mins"),
    Metadata(basename="SHR2", label="Heart rate (pre-sleep) - 2 mins"),
    Metadata(basename="SHR3", label="Heart rate (pre-sleep) - 4 mins"),
    Metadata(basename="SHR4", label="Heart rate (post-sleep) - 0 mins"),
    Metadata(basename="SHR5", label="Heart rate (post-sleep) - 2 mins"),
    Metadata(basename="SHR6", label="Heart rate (post-sleep) - 4 mins"),
    Metadata(basename="CYC1", label="Resistance (cycling - stage 1)", field_width=4, decimals=1),
    Metadata(basename="CYC2", label="Resistance (cycling - stage 2)", field_width=4, decimals=1),
    Metadata(basename="CYC3", label="Resistance (cycling - stage 3)", field_width=4, decimals=1),
    Metadata(
        basename="PWC170", label="Physical Work Capacity at 170 bpm", field_width=5, decimals=2
    ),
    Metadata(
        basename="TECH",
        label="Cycling technique",
        field_width=1,
        var_type="ordinal",
        field_values={"1": "Good", "2": "Suspect", "3": "Poor"},
    ),
    Metadata(
        basename="BPSL", label="Time BP assessment before sleep", field_type="Time", field_width=8
    ),
    Metadata(basename="SLPT", label="Time lights out", field_type="Time", field_width=8),
    Metadata(
        basename="WKBP", label="Time BP assessment after waking", field_type="Time", field_width=8
    ),
    Metadata(basename="WKT", label="Time woke up", field_type="Time", field_width=8),
    Metadata(basename="SPRAT", label="Time set up started", field_type="Time", field_width=8),
    Metadata(
        basename="XCAR",
        label="Completed cardiovascular endurance test",
        field_width=1,
        field_values={0: "No", 1: "Yes"},
    ),
]
